# Build - Build necessary JS files
# Test - Run tests
# Deploy - Deploy application to S3/ElasticBeanstalk
stages:
  - build
  - test
  - release
  - deploy

# Configuration
variables:
  AWS_ACCESS_KEY_ID: "" # Example for access key

# Job: Build
# Installs npm packages, transpiles ES6 -> ES5
# Passes node_modules/, dist/ onto next steps using artifacts
build:
  stage: build
  script:
    - cnpm install
    - NODE_ENV=production npm run build
  artifacts:
    paths:
      - dist/

# Job: Test
# Run tests against our application
# If this fails, we do not deploy
test:
  stage: test
  script:
    - cnpm install
    - npm run lint
    - npm run test

release-image:
  stage: release
  script:
    - cnpm install
    - npm run build:docker
  only:
    - master

# Job: Deploy
# Zips the contents of our built application, uploads to S3
# Configures a new EB version and switches to that version
deploy:
  stage: deploy
  script:
    - ssh root@your-machine "mkdir -p /path/to/deploy"
    - npm run deploy -- root@your-machine:/path/to/deploy/
  only:
    - master
