# Build - Build necessary JS files
# Test - Run tests
# Deploy - Deploy application to S3/ElasticBeanstalk
stages:
  - build
  - test
  - release
  - deploy

# Configuration
variables:
  AWS_ACCESS_KEY_ID: "" # Example for access key

cache:
  paths:
    - node_modules/
    - dist/
  key: ${CI_BUILD_REF_NAME}
  untracked: true

# Job: Build
# Installs npm packages, transpiles ES6 -> ES5
# Passes node_modules/, dist/ onto next steps using artifacts
build:
  stage: build
  script:
    - cnpm install
    - NODE_ENV=production npm run build
  artifacts:
    paths:
      - dist/

# Job: Test
# Run tests against our application
# If this fails, we do not deploy
test:
  stage: test
  script:
    - npm run lint
    - npm run test

release-image:
  stage: release
  script:
    - docker build -t zzswang/react-app-sketch:${CI_BUILD_TAG} .
  only:
    - tags

# Job: Deploy
# Zips the contents of our built application, uploads to S3
# Configures a new EB version and switches to that version
deploy-demo:
  stage: deploy
  script:
    - npm run deploy -- root@yourmachine:/var/www/app
  only:
    - master
